Xhibiter/Xhibiter/Controllers/NFTController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Nethereum.Web3;
using Xhibiter.DAL;
using Xhibiter.Models;
using Xhibiter.Utilities;
using Xhibiter.ViewModels;

namespace Xhibiter.Controllers
{
    public class NFTController : Controller
    {
        UserManager<NFTUser> _userManager { get; }
        AppDbContext _context { get;}
        IWebHostEnvironment _env { get; }
        public NFTController(AppDbContext context, IWebHostEnvironment env, UserManager<NFTUser> userManager)
        {
            _context = context;
            _env = env;
            _userManager = userManager;
        }

        public IActionResult Delete(int? id)
        {
            if (id is null || id <= 0) return BadRequest();
            NFT nft = _context.NFTs.Include(n=>n.Metadata).Include(n=>n.Sales).Include(n=>n.Auction).ThenInclude(a=>a.Bids).FirstOrDefault(n=>n.Id==id);
            if (nft is null) return NotFound();
            _context.NFTs.Remove(nft);
            nft.Metadata.MediaUrl.DeleteFile(_env.WebRootPath, "assets/media/nft");

            _context.NFTMetadatas.Remove(nft.Metadata);
            _context.Bids.RemoveRange(nft.Auction.Bids);
            _context.Auctions.Remove(nft.Auction);
            _context.Sales.RemoveRange(nft.Sales);
            _context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
        public  async Task<IActionResult> Index(int? id)
        {
            if (id is null || id <= 0) return BadRequest();
            NFT nft = _context.NFTs.Include(n=>n.Metadata).ThenInclude(n=>n.Creator).ThenInclude(c=>c.Profile)
                .Include(n=>n.Owner).ThenInclude(n=>n.Profile).FirstOrDefault(n => n.Id == id);
            if (nft is null) return NotFound();
            var auction = _context.Auctions.Include(n=>n.Winner).ThenInclude(w=>w.NFTUser).FirstOrDefault(a => a.NFTId == id);
            var colname = _context.NFTCollections.FirstOrDefault(n=>n.Id == nft.CollectionId).Name;
            NFTDetailVM NFTDetail = new()
            {
                CollectionName = colname,
                NFT = nft,
                NFTs = _context.NFTs.Include(n=>n.Metadata).Where(n => n.CollectionId == nft.CollectionId && n.Id != nft.Id).Where(n=>n.IsSale),
                Auction = auction,
                Bids = _context.Bids.Include(b=>b.Bidder).ThenInclude(b=>b.NFTUser).Where(b => auction != null && b.AuctionId == auction.Id).OrderByDescending(b => b.Amount),
                Sales = _context.Sales.Include(s=>s.From).Include(s=>s.To).Where(s => s.NFTId == id),
            };
            if (auction != null)
            {
                await nft.CompleteAuction(auction,_context);
            }
            return View(NFTDetail);
        }
        public IActionResult FilterByCategory(string categoryName)
        {
            var nfts = _context.NFTs.Include(n => n.Metadata).Include(n => n.Auction).Include(n=>n.NFTCategories).Where(n => n.NFTCategories
                                 .Any(nc => nc.Category.Name == categoryName && n.IsSale)).Take(20);
            if (categoryName == "All")
            {
                nfts = _context.NFTs.Include(n => n.Metadata).ThenInclude(m => m.Creator).ThenInclude(c => c.Profile).Include(n => n.Auction).Where(n=>n.IsSale);
            }

            return PartialView("_OnSalePartial", nfts);
        }
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.Collections = new SelectList(_context.NFTCollections.Where(n => n.Creator.NFTUser.UserName == User.Identity.Name), nameof(NFTCollection.Id), nameof(NFTCollection.Name));
            ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateNFTVM createNFT)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Collections = new SelectList(_context.NFTCollections.Where(n => n.Creator.NFTUser.UserName == User.Identity.Name), nameof(NFTCollection.Id), nameof(NFTCollection.Name));
                ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                return View();
            }
            if (_context.NFTs.Any(n => n.Name == createNFT.Name))
            {
                ModelState.AddModelError("Name", "There is already an nft with this name!");
                ViewBag.Collections = new SelectList(_context.NFTCollections.Where(n => n.Creator.NFTUser.UserName == User.Identity.Name), nameof(NFTCollection.Id), nameof(NFTCollection.Name));
                ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                return View();
            }
            IFormFile media = createNFT.Media;
            var res = media.ContentType;
                string result = media.CheckValidate(30);
                if (result.Length > 0)
                {
                    ModelState.AddModelError("Media", result);
                    ViewBag.Collections = new SelectList(_context.NFTCollections.Where(n => n.Creator.NFTUser.UserName == User.Identity.Name), nameof(NFTCollection.Id), nameof(NFTCollection.Name));
                    ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                    return View();
            }
            if (!_context.NFTCollections.Any(c => c.Id == createNFT.CollectionId))
            {
                ModelState.AddModelError("CollectionIds", "There is no matched collection with this id!");
                ViewBag.Collections = new SelectList(_context.NFTCollections.Where(n => n.Creator.NFTUser.UserName == User.Identity.Name), nameof(NFTCollection.Id), nameof(NFTCollection.Name));
                ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                return View();
            }
            foreach (int categoryId in (createNFT.CategoryIds ?? new List<int>()))
            {
                if (!_context.Categories.Any(c => c.Id == categoryId))
                {
                    ModelState.AddModelError("CategoryIds", "There is no matched category with this id!");
                    ViewBag.Collections = new SelectList(_context.NFTCollections.Where(n => n.Creator.NFTUser.UserName == User.Identity.Name), nameof(NFTCollection.Id), nameof(NFTCollection.Name));
                    ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                    return View();
                }
            }
            var categories = _context.Categories.Where(ca => createNFT.CategoryIds.Contains(ca.Id));
            NFTUser user = await _userManager.FindByNameAsync(User.Identity.Name);
            if (user is null) return BadRequest();
            NFTMetadata metadata = new NFTMetadata()
            {
                TokenId = "",
                ExternalLink = createNFT.ExternalLink,
                Creator = user,
                CreatedDate = DateTime.Now,
            };
            if (res.Contains("video/"))
            {
                metadata.MediaType = "video";
                metadata.MediaUrl = media.SaveFile(Path.Combine(_env.WebRootPath, "assets", "media", "nft"));
            }
            else if (res.Contains("audio/"))
            {
                metadata.MediaType = "audio";
                metadata.MediaUrl = media.SaveFile(Path.Combine(_env.WebRootPath, "assets", "media", "nft"));

            }
            else
            {
                metadata.MediaType = "image";
                metadata.MediaUrl = media.SaveImage(Path.Combine(_env.WebRootPath, "assets", "media", "nft"));

            }
            await _context.NFTMetadatas.AddAsync(metadata);
            NFT nft = new NFT
            {
                Owner = user,
                Name = createNFT.Name,
                Description = createNFT.Description,
                Price = createNFT.Price,
                IsSale = createNFT.IsSale,
                Metadata = metadata,
                CollectionId = createNFT.CollectionId
            };
            await _context.NFTs.AddAsync(nft);
            foreach (var item in categories)
            {
                await _context.NFTCategories.AddAsync(new NFTCategory { NFT = nft, CategoryId = item.Id });
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null || id <= 0) return BadRequest();
            NFT exist = await _context.NFTs.Include(n=>n.Metadata).Include(n=>n.NFTCategories)
                .FirstOrDefaultAsync(n=>n.Id == id);
            if (exist is null) return NotFound();
            EditNFTVM edit = new EditNFTVM()
            {
                Name = exist.Name,
                Description = exist.Description,
                CategoryIds = exist.NFTCategories.Select(n => n.CategoryId).ToList<int>(),
                CollectionId = exist.CollectionId,
                ExternalLink = exist.Metadata.ExternalLink,
                IsSale = exist.IsSale,
                Price = exist.Price,
            };
            ViewBag.Collections = new SelectList(_context.NFTCollections.Where(n => n.Creator.NFTUser.UserName == User.Identity.Name), nameof(NFTCollection.Id), nameof(NFTCollection.Name));
            ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
            ViewBag.Image = exist.Metadata.MediaUrl;
            return View(edit);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int? id,EditNFTVM editNFT)
        {

Xhibiter/Xhibiter/Views/Shared/_AuctionSliderPartial.cshtml
@model IEnumerable<NFT>
@foreach (var item in Model)
{
    <div class="swiper-slide">
<article>
<div
    class="block rounded-2.5xl border border-jacarta-100 bg-white p-[1.1875rem] transition-shadow hover:shadow-lg dark:border-jacarta-700 dark:bg-jacarta-700"
>
    <figure class="relative">
    <a 
        asp-action="Index" asp-controller="NFT" asp-route-id="@item.Id">
        @if (item.Metadata.MediaType == "audio")
        {
            <div style="position:relative;">
              <img src="~/assets/images/default/default-music.gif" style="width:230px;height:230px;">
              <audio  controls style="position:absolute;top:0;left:0;width:100%;height:100%;z-index:2;background:transparent;">
                <source src="~/assets/media/nft/@item.Metadata.MediaUrl"  type="audio/mp3">
              </audio>
            </div>
        }
        else if(item.Metadata.MediaType == "video")
        {
            <video
                controls loop muted poster="~/assets/images/default/default-video.jpg"
                style="height:230px;width:230px;max-width:none;max-block-size:none;max-height:none;"
                alt="item"
                class="w-full rounded-[0.625rem]">
            <source src="~/assets/media/nft/@item.Metadata.MediaUrl">
            </video>
        }
        else
        {
        <img
            style="height:230px;"
        src="~/assets/media/nft/@item.Metadata.MediaUrl"
        alt="item 1"
        class="w-full rounded-[0.625rem]"
        loading="lazy"
        />
        }
    </a>
<div
class="absolute bottom-4 left-1/2 flex -translate-x-1/2 items-center justify-center space-x-1 rounded-full bg-white py-2.5 px-6 text-2xs font-medium"
>
<span
    class="h-3.5 w-3.5 shrink-0 bg-contain bg-center"
    style="
    background-image: url(https://cdn.jsdelivr.net/npm/emoji-datasource-apple@7.0.2/img/apple/64/23f3.png);
    "
></span>
<span
    class="js-countdown-timer shrink-0 whitespace-nowrap text-jacarta-700"
    data-countdown="@item.Auction?.EndTime.ToString()"
    data-expired="This auction has ended"
></span>
<span class="js-countdown-left" data-countdownLeft="left"></span>
</div>
    </figure>
    <div class="mt-7 flex items-center justify-between">
    <a asp-action="Index" asp-controller="NFT" asp-route-id="@item.Id">
        <span class="font-display text-base text-jacarta-700 hover:text-accent dark:text-white"
        >@item.Name</span
        >
    </a>
    <span
        class="flex items-center whitespace-nowrap rounded-md border border-jacarta-100 py-1 px-2 dark:border-jacarta-600"
    >
        <span data-tippy-content="ETH">
        <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            x="0"
            y="0"
            viewBox="0 0 1920 1920"
            xml:space="preserve"
            class="h-4 w-4"
        >
            <path fill="#8A92B2" d="M959.8 80.7L420.1 976.3 959.8 731z" />
            <path
            fill="#62688F"
            d="M959.8 731L420.1 976.3l539.7 319.1zm539.8 245.3L959.8 80.7V731z"
            />
            <path fill="#454A75" d="M959.8 1295.4l539.8-319.1L959.8 731z" />
            <path fill="#8A92B2" d="M420.1 1078.7l539.7 760.6v-441.7z" />
            <path fill="#62688F" d="M959.8 1397.6v441.7l540.1-760.6z" />
        </svg>
        </span>
        <span class="text-sm font-medium tracking-tight text-green">@item.Auction?.CurrentPrice ETH</span>
    </span>
    </div>
    <div class="mt-2 text-sm">
    <span class="dark:text-jacarta-300">Current Bid</span>
    <span class="highestt-@item.Auction.Id text-jacarta-700 dark:text-jacarta-100">@item.Auction?.CurrentPrice ETH</span>
    </div>

    <div class="mt-8 flex items-center justify-between">
    <button
        data-username="@User.Identity.Name"
        data-auctionid="@item.Auction?.Id"
        type="button"
        class="bidbutton font-display text-sm font-semibold text-accent"
        data-bs-toggle="modal"
        data-bs-target="#placeBidModal"
    >
        Place bid
    </button>

@*    <div class="flex items-center space-x-1">
        <span
        class="js-likes relative cursor-pointer before:absolute before:h-4 before:w-4 before:bg-[url('../img/heart-fill.svg')] before:bg-cover before:bg-center before:bg-no-repeat before:opacity-0"
        data-tippy-content="Favorite"
        >
        <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            width="24"
            height="24"
            class="h-4 w-4 fill-jacarta-500 hover:fill-red dark:fill-jacarta-200 dark:hover:fill-red"
        >
            <path fill="none" d="M0 0H24V24H0z" />
            <path
            d="M12.001 4.529c2.349-2.109 5.979-2.039 8.242.228 2.262 2.268 2.34 5.88.236 8.236l-8.48 8.492-8.478-8.492c-2.104-2.356-2.025-5.974.236-8.236 2.265-2.264 5.888-2.34 8.244-.228zm6.826 1.641c-1.5-1.502-3.92-1.563-5.49-.153l-1.335 1.198-1.336-1.197c-1.575-1.412-3.99-1.35-5.494.154-1.49 1.49-1.565 3.875-.192 5.451L12 18.654l7.02-7.03c1.374-1.577 1.299-3.959-.193-5.454z"
            />
        </svg>
        </span>
        <span class="text-sm dark:text-jacarta-200">159</span>
    </div>*@
    </div>
</div>
</article>
	</div>
}

Xhibiter/Xhibiter/Views/Shared/_AuctionedPartial.cshtml
@model IEnumerable<NFT>
@foreach (var item in Model)
{
<article>
<div
    class="block rounded-2.5xl border border-jacarta-100 bg-white p-[1.1875rem] transition-shadow hover:shadow-lg dark:border-jacarta-700 dark:bg-jacarta-700"
>
    <figure class="relative">
    <a 
        asp-action="Index" asp-controller="NFT" asp-route-id="@item.Id">
        @if (item.Metadata.MediaType == "audio")
        {
            <div style="position:relative;">
              <img src="~/assets/images/default/default-music.gif" style="width:230px;height:230px;">
              <audio  style="position:absolute;top:0;left:0;width:100%;height:100%;z-index:2;background:transparent;">
                <source src="~/assets/media/nft/@item.Metadata.MediaUrl"  type="audio/mp3">
              </audio>
            </div>
        }
        else if(item.Metadata.MediaType == "video")
        {
            <video
                 loop muted poster="~/assets/images/default/default-video.jpg"
                style="height:230px;width:230px;max-width:none;max-block-size:none;max-height:none;"
                alt="item"
                class="w-full rounded-[0.625rem]">
            <source src="~/assets/media/nft/@item.Metadata.MediaUrl">
            </video>
        }
        else
        {
        <img
            style="height:230px;"
        src="~/assets/media/nft/@item.Metadata.MediaUrl"
        alt="item 1"
        class="w-full rounded-[0.625rem]"
        loading="lazy"
        />
        }
    </a>
<div
class="absolute bottom-4 left-1/2 flex -translate-x-1/2 items-center justify-center space-x-1 rounded-full bg-white py-2.5 px-6 text-2xs font-medium"
>
<span
    class="h-3.5 w-3.5 shrink-0 bg-contain bg-center"
    style="
    background-image: url(https://cdn.jsdelivr.net/npm/emoji-datasource-apple@7.0.2/img/apple/64/23f3.png);
    "
></span>
<span
    class="js-countdown-timer shrink-0 whitespace-nowrap text-jacarta-700"
    data-countdown="@item.Auction?.EndTime.ToString()"
    data-expired="This auction has ended"
></span>
<span class="js-countdown-left" data-countdownLeft="left"></span>
</div>
    </figure>
    <div class="mt-7 flex items-center justify-between">
    <a asp-action="Index" asp-controller="NFT" asp-route-id="@item.Id">
        <span class="font-display text-base text-jacarta-700 hover:text-accent dark:text-white"
        >@item.Name</span
        >
    </a>
    <span
        class="flex items-center whitespace-nowrap rounded-md border border-jacarta-100 py-1 px-2 dark:border-jacarta-600"
    >
        <span data-tippy-content="ETH">
        <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            x="0"
            y="0"
            viewBox="0 0 1920 1920"
            xml:space="preserve"
            class="h-4 w-4"
        >
            <path fill="#8A92B2" d="M959.8 80.7L420.1 976.3 959.8 731z" />
            <path
            fill="#62688F"
            d="M959.8 731L420.1 976.3l539.7 319.1zm539.8 245.3L959.8 80.7V731z"
            />
            <path fill="#454A75" d="M959.8 1295.4l539.8-319.1L959.8 731z" />
            <path fill="#8A92B2" d="M420.1 1078.7l539.7 760.6v-441.7z" />
            <path fill="#62688F" d="M959.8 1397.6v441.7l540.1-760.6z" />
        </svg>
        </span>
        <span class="text-sm font-medium tracking-tight text-green">@item.Price ETH</span>
    </span>
    </div>
    <div class="mt-2 text-sm">
    <span class="dark:text-jacarta-300">Current Bid</span>
    <span class="highestt-@item.Auction.Id text-jacarta-700 dark:text-jacarta-100">@item.Auction?.CurrentPrice ETH</span>
    </div>

    <div class="mt-8 flex items-center justify-between">
    <button
        data-username="@User.Identity.Name"
        data-auctionid="@item.Auction?.Id"
        type="button"
        class="bidbutton font-display text-sm font-semibold text-accent"
        data-bs-toggle="modal"
        data-bs-target="#placeBidModal"
    >
        Place bid
    </button>

@*    <div class="flex items-center space-x-1">
        <span
        class="js-likes relative cursor-pointer before:absolute before:h-4 before:w-4 before:bg-[url('../img/heart-fill.svg')] before:bg-cover before:bg-center before:bg-no-repeat before:opacity-0"
        data-tippy-content="Favorite"
        >
        <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            width="24"
            height="24"
            class="h-4 w-4 fill-jacarta-500 hover:fill-red dark:fill-jacarta-200 dark:hover:fill-red"
        >
            <path fill="none" d="M0 0H24V24H0z" />
            <path
            d="M12.001 4.529c2.349-2.109 5.979-2.039 8.242.228 2.262 2.268 2.34 5.88.236 8.236l-8.48 8.492-8.478-8.492c-2.104-2.356-2.025-5.974.236-8.236 2.265-2.264 5.888-2.34 8.244-.228zm6.826 1.641c-1.5-1.502-3.92-1.563-5.49-.153l-1.335 1.198-1.336-1.197c-1.575-1.412-3.99-1.35-5.494.154-1.49 1.49-1.565 3.875-.192 5.451L12 18.654l7.02-7.03c1.374-1.577 1.299-3.959-.193-5.454z"
            />
        </svg>
        </span>
        <span class="text-sm dark:text-jacarta-200">159</span>
    </div>*@
    </div>
</div>
</article>
	
}

Xhibiter/Xhibiter/Views/Shared/_OnSalePartial.cshtml
@model IEnumerable<NFT>
  
@foreach (var item in Model)
                {
                <article>
                  <div
                    class="block rounded-2.5xl border border-jacarta-100 bg-white p-[1.1875rem] transition-shadow hover:shadow-lg dark:border-jacarta-700 dark:bg-jacarta-700"
                  >
                    <figure class="relative">
                                
                        <a asp-action="Index" asp-controller="NFT" asp-route-id="@item.Id">
                @if (item.Metadata.MediaType == "audio")
                {
                    <div style="position:relative;">
                        <img src="~/assets/images/default/default-music.gif" style="width:230px;height:230px;">
                        <audio  controls style="position:absolute;top:0;left:0;width:100%;height:100%;z-index:2;background:transparent;">
                        <source src="~/assets/media/nft/@item.Metadata.MediaUrl"  type="audio/mp3">
                        </audio>
                    </div>
                }
                else if(item.Metadata.MediaType == "video")
                {
                    <video
                        controls loop muted poster="~/assets/images/default/default-video.jpg"
                        style="height:230px;width:230px;max-width:none;max-block-size:none;max-height:none;"
                        alt="item"
                        class="w-full rounded-[0.625rem]">
                    <source src="~/assets/media/nft/@item.Metadata.MediaUrl">
                    </video>
                }
                else
                {
                <img
                    style="height:230px;"
                src="~/assets/media/nft/@item.Metadata.MediaUrl"
                alt="item 1"
                class="w-full rounded-[0.625rem]"
                loading="lazy"
                />
                }
            </a>
@*                      <div
                        class="absolute top-3 right-3 flex items-center space-x-1 rounded-md bg-white p-2 dark:bg-jacarta-700"
                      >
                        <span
                          class="js-likes relative cursor-pointer before:absolute before:h-4 before:w-4 before:bg-[url('/assets/img/heart-fill.svg')] before:bg-cover before:bg-center before:bg-no-repeat before:opacity-0"
                          data-tippy-content="Favorite"
                        >
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            viewBox="0 0 24 24"
                            width="24"
                            height="24"
                            class="h-4 w-4 fill-jacarta-500 hover:fill-red dark:fill-jacarta-200 dark:hover:fill-red"
                          >
                            <path fill="none" d="M0 0H24V24H0z" />
                            <path
                              d="M12.001 4.529c2.349-2.109 5.979-2.039 8.242.228 2.262 2.268 2.34 5.88.236 8.236l-8.48 8.492-8.478-8.492c-2.104-2.356-2.025-5.974.236-8.236 2.265-2.264 5.888-2.34 8.244-.228zm6.826 1.641c-1.5-1.502-3.92-1.563-5.49-.153l-1.335 1.198-1.336-1.197c-1.575-1.412-3.99-1.35-5.494.154-1.49 1.49-1.565 3.875-.192 5.451L12 18.654l7.02-7.03c1.374-1.577 1.299-3.959-.193-5.454z"
                            />
                          </svg>
                        </span>
                        <span class="text-sm dark:text-jacarta-200">15</span>
                      </div>*@
                    </figure>
                    <div class="mt-7 flex items-center justify-between">
                      <a asp-action="Index" asp-controller="NFT" asp-route-id="@item.Id">
                        <span class="font-display text-base text-jacarta-700 hover:text-accent dark:text-white"
                          >@item.Name</span
                        >
                      </a>
@*                      <div class="dropup rounded-full hover:bg-jacarta-100 dark:hover:bg-jacarta-600">
                        <a
                          href="#"
                          class="dropdown-toggle inline-flex h-8 w-8 items-center justify-center text-sm"
                          role="button"
                          id="itemActions"
                          data-bs-toggle="dropdown"
                          aria-expanded="false"
                        >
                          <svg
                            width="16"
                            height="4"
                            viewBox="0 0 16 4"
                            fill="none"
                            xmlns="http://www.w3.org/2000/svg"
                            class="fill-jacarta-500 dark:fill-jacarta-200"
                          >
                            <circle cx="2" cy="2" r="2" />
                            <circle cx="8" cy="2" r="2" />
                            <circle cx="14" cy="2" r="2" />
                          </svg>
                        </a>
                        <div
                          class="dropdown-menu dropdown-menu-end z-10 hidden min-w-[200px] whitespace-nowrap rounded-xl bg-white py-4 px-2 text-left shadow-xl dark:bg-jacarta-800"
                          aria-labelledby="itemActions"
                        >
                          <button
                            class="block w-full rounded-xl px-5 py-2 text-left font-display text-sm transition-colors hover:bg-jacarta-50 dark:text-white dark:hover:bg-jacarta-600"
                          >
                            New bid
                          </button>
                          <hr class="my-2 mx-4 h-px border-0 bg-jacarta-100 dark:bg-jacarta-600" />
                          <button
                            class="block w-full rounded-xl px-5 py-2 text-left font-display text-sm transition-colors hover:bg-jacarta-50 dark:text-white dark:hover:bg-jacarta-600"
                          >
                            Refresh Metadata
                          </button>
                          <button
                            class="block w-full rounded-xl px-5 py-2 text-left font-display text-sm transition-colors hover:bg-jacarta-50 dark:text-white dark:hover:bg-jacarta-600"
                          >
                            Share
                          </button>
                          <button
                            class="block w-full rounded-xl px-5 py-2 text-left font-display text-sm transition-colors hover:bg-jacarta-50 dark:text-white dark:hover:bg-jacarta-600"
                          >
                            Report
                          </button>
                        </div>
                      </div>*@
                    </div>
                    <div class="mt-2 text-sm">
                      <span class="mr-1 text-jacarta-700 dark:text-jacarta-200">From @item.Price ETH</span>
                    </div>

                    <div class="mt-8 flex items-center justify-between">
                      <a asp-action="Index" asp-controller="NFT" asp-route-id="@item.Id"
                        class="font-display text-sm font-semibold text-accent"
                      >
                        Buy now
                      </a>
                      <a asp-action="Index" asp-controller="NFT" asp-route-id="@item.Id" class="group flex items-center">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          viewBox="0 0 24 24"
                          width="24"
                          height="24"
                          class="mr-1 mb-[3px] h-4 w-4 fill-jacarta-500 group-hover:fill-accent dark:fill-jacarta-200"
                        >
                          <path fill="none" d="M0 0H24V24H0z" />
                          <path
                            d="M12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12h2c0 4.418 3.582 8 8 8s8-3.582 8-8-3.582-8-8-8C9.25 4 6.824 5.387 5.385 7.5H8v2H2v-6h2V6c1.824-2.43 4.729-4 8-4zm1 5v4.585l3.243 3.243-1.415 1.415L11 12.413V7h2z"
                          />
                        </svg>
                        <span class="font-display text-sm font-semibold group-hover:text-accent dark:text-jacarta-200"
                          >View History</span
                        >
                      </a>
                    </div>
                  </div>
                </article>
                    
                }