Xhibiter/Xhibiter/ViewModels/Collection/CreateCollectionVM.cs
namespace Xhibiter.ViewModels
{
    public class CreateCollectionVM
    {
        public string Name { get; set; }
        public IFormFile CoverImg { get; set; }
        public IFormFile LogoImg { get; set; }
        public IFormFile MainImg { get; set; }
        public string? Description { get; set; }
        public int CategoryId { get; set; }
    }
}

Xhibiter/Xhibiter/ViewModels/Collection/EditCollectionVM.cs
namespace Xhibiter.ViewModels
{
    public class EditCollectionVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string? Description { get; set; }
        public IFormFile? CoverImg { get; set; }
        public IFormFile?LogoImg { get; set; }
        public IFormFile? MainImg { get; set; }
        public int CategoryId { get; set; }
    }
}

Xhibiter/Xhibiter/Areas/Manage/Controllers/CollectionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Xhibiter.DAL;
using Xhibiter.Models;
using Xhibiter.ViewModels;
using Microsoft.AspNetCore.Authorization;


namespace Xhibiter.Areas.Manage.Controllers
{
    [Area("Manage")]
    [Authorize(Roles = "Admin")]

    public class CollectionController : Controller
    {
        AppDbContext _context { get; }

        public CollectionController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult List(int page = 1)
        {
            PaginateVM<NFTCollection> paginateVM = new PaginateVM<NFTCollection>();
            paginateVM.MaxPageCount = (int)Math.Ceiling((decimal)_context.NFTCollections.Count() / 5);
            paginateVM.CurrentPage = page;
            if (page > paginateVM.MaxPageCount || page < 1) return BadRequest();
            paginateVM.Items = _context.NFTCollections?.Skip((page - 1) * 5).Take(5).Include(n=>n.Category).Include(p => p.Creator).ThenInclude(c=>c.NFTUser).OrderByDescending(n=>n.CreationDate);
            return View(paginateVM);
        }
        public IActionResult Details(int id)
        {
            var nfts =  _context.NFTs.Include(n => n.Metadata).ThenInclude(n => n.Creator).Include(n => n.Owner).OrderByDescending(n => n.Metadata.CreatedDate).Where(n=>n.CollectionId == id);
            return View(nfts);
        }
    }
}

Xhibiter/Xhibiter/Controllers/CollectionController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Xhibiter.DAL;
using Xhibiter.Models;
using Xhibiter.Utilities;
using Xhibiter.ViewModels;

namespace Xhibiter.Controllers
{
    public class CollectionController : Controller
    {
        AppDbContext _context { get; }
        IWebHostEnvironment _env { get; }
        UserManager<NFTUser> _userManager { get; }

        public CollectionController(AppDbContext context, IWebHostEnvironment env, UserManager<NFTUser> userManager)
        {
            _context = context;
            _env = env;
            _userManager = userManager;
        }

        public IActionResult Explore()
        {
            var collections = _context.NFTCollections.Include(n => n.Creator).ThenInclude(n => n.NFTUser).Include(n => n.NFTs);
            ViewBag.Categories = _context.Categories.ToList();
            return View(collections);
        }

        public ActionResult FilterByCategory(string categoryName)
        {
            var collections = _context.NFTCollections.Include(n => n.Creator).ThenInclude(n => n.NFTUser).Include(n => n.NFTs).Where(c => c.Category.Name == categoryName);
            if (categoryName == "All")
            {
                collections = _context.NFTCollections.Include(n => n.Creator).ThenInclude(n => n.NFTUser).Include(n => n.NFTs);
            }

            return PartialView("_CollectionsPartial", collections);
        }
        public IActionResult Index(int? id)
        {
            NFTCollection collection = _context.NFTCollections.Include(n=>n.NFTs.Where(n => n.IsSale || n.IsAuctioned)).ThenInclude(n=>n.Owner).ThenInclude(n=>n.Profile)
                .Include(n => n.NFTs.Where(n=>n.IsSale || n.IsAuctioned)).ThenInclude(n=>n.Metadata).ThenInclude(m=>m.Creator)
                .Include(n => n.Creator).ThenInclude(c=>c.NFTUser).FirstOrDefault(n => n.Id == id);
            if (User.Identity.IsAuthenticated && User.Identity.Name == collection.Creator.NFTUser.UserName)
            {
                collection = _context.NFTCollections.Include(n => n.NFTs).ThenInclude(n => n.Owner).ThenInclude(n => n.Profile)
                .Include(n => n.NFTs).ThenInclude(n => n.Metadata).ThenInclude(m => m.Creator)
                .Include(n => n.Creator).ThenInclude(c => c.NFTUser).FirstOrDefault(n => n.Id == id);
            }
                return View(collection);
        }
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCollectionVM collection)
        {
            if (!ModelState.IsValid) 
            {
                ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                return View();
            }
            if (_context.NFTCollections.Any(n => n.Name == collection.Name))
            {
                ModelState.AddModelError("Name", "This name is already taken!");
                ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                return View();
            }
            IFormFile cover = collection.CoverImg;
            IFormFile logo = collection.LogoImg;
            IFormFile main = collection.MainImg;
            string result = cover.CheckValidate2(19);
            if (result.Length > 0)
            {
                ModelState.AddModelError("CoverImg", result);
                ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                return View();
            };
            result = logo.CheckValidate2(10);
            if (result.Length > 0)
            {
                ModelState.AddModelError("LogoImg", result);
                ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                return View();
            };
            result = logo.CheckValidate2(10);
            if (result.Length > 0)
            {
                ModelState.AddModelError("MainImg", result);
                ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                return View();
            };
            if (!_context.Categories.Any(c=>c.Id == collection.CategoryId))
            {
                ModelState.AddModelError("CategoryId", "There is no category in this id!");
                ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                return View();
            };
            char[] disallowedChars = new char[] { '#', '*', '$','/',':','<','>','?','|'};

            if (collection.Name.IndexOfAny(disallowedChars) != -1)
            {
                ModelState.AddModelError("Name", " Collection name can't contain *,#,$,/,:,<,>,?,|");
                ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                return View();
            }
            UserProfile user = await _context.UserProfiles.FirstOrDefaultAsync(u => u.NFTUser.UserName == User.Identity.Name);
            if (user == null) return BadRequest();
            NFTCollection nFTCollection = new NFTCollection()
            {
                Name = collection.Name,
                Description = collection.Description,
                CreationDate = DateTime.Now,
                Creator = user,
                CategoryId = collection.CategoryId,
                CoverImgUrl = cover.SaveImage(Path.Combine(_env.WebRootPath, "assets", "images", "users",User.Identity.Name,"collections",collection.Name)),
                LogoImgUrl = logo.SaveImage(Path.Combine(_env.WebRootPath, "assets", "images", "users",User.Identity.Name,"collections",collection.Name)),
                MainImgUrl = main.SaveImage(Path.Combine(_env.WebRootPath, "assets", "images", "users",User.Identity.Name,"collections",collection.Name)),
            };
            await _context.NFTCollections.AddAsync(nFTCollection);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Profile",new {username = User.Identity.Name});
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null || id <= 0) return BadRequest();
            NFTCollection exist = await _context.NFTCollections.FirstOrDefaultAsync(n => n.Id == id);
            if (exist is null) return NotFound();
            EditCollectionVM edit = new EditCollectionVM()
            {
                Id = exist.Id,
                Name = exist.Name,
                Description = exist.Description,
                CategoryId = exist.CategoryId,
            };
            ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
            ViewBag.Imgs = new string[] { exist.MainImgUrl, exist.LogoImgUrl, exist.CoverImgUrl };
            return View(edit);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int? id, EditCollectionVM editCollection)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                var existColl = await _context.NFTCollections.FirstOrDefaultAsync(n => n.Id == id);
                ViewBag.Imgs = new string[] { existColl.MainImgUrl, existColl.LogoImgUrl, existColl.CoverImgUrl };
                EditCollectionVM edit = new EditCollectionVM()
                {
                    Id = existColl.Id,
                    Name = existColl.Name,
                    Description = existColl.Description,
                    CategoryId = existColl.CategoryId,
                };
                return View(edit);
            }
            if (_context.NFTCollections.Any(n => n.Name == editCollection.Name && n.Id != editCollection.Id))
            {
                ModelState.AddModelError("Name", "This name is already taken!");
                ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                var existColl = await _context.NFTCollections.FirstOrDefaultAsync(n => n.Id == id);
                ViewBag.Imgs = new string[] { existColl.MainImgUrl, existColl.LogoImgUrl, existColl.CoverImgUrl };
                EditCollectionVM edit = new EditCollectionVM()
                {
                    Id = existColl.Id,
                    Name = existColl.Name,
                    Description = existColl.Description,
                    CategoryId = existColl.CategoryId,
                };
                return View(edit);
            }
            var cover = editCollection.CoverImg;
            var main = editCollection.MainImg;
            var logo = editCollection.LogoImg;
            string result = cover?.CheckValidate(10);
            if (cover != null)
            {
                if (result.Length > 0)
                {
                    ModelState.AddModelError("CoverImg", result);
                    ViewBag.Categories = new SelectList(_context.Categories, nameof(Category.Id), nameof(Category.Name));
                    var existColl = await _context.NFTCollections.FirstOrDefaultAsync(n => n.Id == id);
                    ViewBag.Imgs = new string[] { existColl.MainImgUrl, existColl.LogoImgUrl, existColl.CoverImgUrl };
                    EditCollectionVM edit = new EditCollectionVM()
                    {
                        Id = existColl.Id,
                        Name = existColl.Name,
                        Description = existColl.Description,
                        CategoryId = existColl.CategoryId,
                    };
                    return View(edit);

Xhibiter/Xhibiter/Views/Collection/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}
@model EditCollectionVM

    <main class="pt-[5.5rem] lg:pt-24">
      <!-- Banner -->
      <form method="post" enctype="multipart/form-data">

      <div class="relative">
            <img src="~/assets/images/users/@User.Identity.Name/collections/@Model.Name/@ViewBag.Imgs[2]" alt="banner" class="h-[18.75rem] w-full object-cover" />
        <div class="container relative -translate-y-4">
          <div
            class="group absolute right-0 bottom-4 flex items-center rounded-lg bg-white py-2 px-4 font-display text-sm hover:bg-accent"
          >
            <input asp-for="CoverImg" accept="image/*" class="absolute inset-0 cursor-pointer opacity-0" />
            <svg
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 24 24"
              width="24"
              height="24"
              class="mr-1 h-4 w-4 fill-jacarta-400 group-hover:fill-white"
            >
              <path fill="none" d="M0 0h24v24H0z"></path>
              <path
                d="M15.728 9.686l-1.414-1.414L5 17.586V19h1.414l9.314-9.314zm1.414-1.414l1.414-1.414-1.414-1.414-1.414 1.414 1.414 1.414zM7.242 21H3v-4.243L16.435 3.322a1 1 0 0 1 1.414 0l2.829 2.829a1 1 0 0 1 0 1.414L7.243 21z"
              ></path>
            </svg>
            <span class="mt-0.5 block group-hover:text-white">Edit cover photo</span>
          </div>
        </div>
      </div>
      <!-- end banner -->

      <!-- Edit Profile -->
      <section class="relative py-16 dark:bg-jacarta-800">
        <picture class="pointer-events-none absolute inset-0 -z-10 dark:hidden">
          <img src="~/assets/img/gradient_light.jpg" alt="gradient" class="h-full w-full" />
        </picture>

        <div class="container">
          <div class="mx-auto max-w-[48.125rem] md:flex">
            <!-- Form -->
            <div class="mb-12 md:w-1/2 md:pr-8">
              <div class="mb-6">
                <label asp-for="Name" class="mb-1 block font-display text-sm text-jacarta-700 dark:text-white"
                  ></label>
                <input asp-for="Name"
                  class="w-full rounded-lg border-jacarta-100 py-3 hover:ring-2 hover:ring-accent/10 focus:ring-accent dark:border-jacarta-600 dark:bg-jacarta-700 dark:text-white dark:placeholder:text-jacarta-300"
                  placeholder="Enter username"
                />
                <span asp-validation-for="Name" class="text-red"></span>
              </div>
              <div class="mb-6">
                <label asp-for="Description" class="mb-1 block font-display text-sm text-jacarta-700 dark:text-white"
                  ></label>
                <textarea
                    asp-for="Description"
                  class="w-full rounded-lg border-jacarta-100 py-3 hover:ring-2 hover:ring-accent/10 focus:ring-accent dark:border-jacarta-600 dark:bg-jacarta-700 dark:text-white dark:placeholder:text-jacarta-300"
                  placeholder="Tell the world your story!"
                ></textarea>
                <span asp-validation-for="Description" class="text-red"></span>
              </div>
                          
              <div class="relative">
              <div>
                <label asp-for="CategoryId" class="mb-2 block font-display text-jacarta-700 dark:text-white">Categories</label>
                <div class="mb-3 flex items-center space-x-2">
                  <p class="text-2xs dark:text-jacarta-300">
                    This is the collection where your item will appear.
                    <span
                      class="inline-block"
                      data-tippy-content="Moving items to a different collection may take up to 30 minutes."
                    >
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        width="24"
                        height="24"
                        class="ml-1 -mb-[3px] h-4 w-4 fill-jacarta-500 dark:fill-jacarta-300"
                      >
                        <path fill="none" d="M0 0h24v24H0z"></path>
                        <path
                          d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm0-2a8 8 0 1 0 0-16 8 8 0 0 0 0 16zM11 7h2v2h-2V7zm0 4h2v6h-2v-6z"
                        ></path>
                      </svg>
                    </span>
                  </p>
                </div>
              </div>
              <div class=" my-1 cursor-pointer">
                  <select asp-for="CategoryId" class=" z-10  w-full whitespace-nowrap rounded-xl bg-white py-4 px-2 text-left shadow-xl dark:bg-jacarta-800">
                      <option selected  disabled>Select collections</option>
                      @foreach(var item in ViewBag.Categories)
                      {
                          <option class="text-jacarta-700 dark:text-white" value="@item.Value">@item.Text</option>
                      }
                  </select>
              </div>
              <span asp-validation-for="CategoryId" class="text-red"></span>
            </div>

              <div class="flex space-x-4 ">
                <button
                  class=" w-36 rounded-full bg-accent py-1 px-8 text-center font-semibold text-white shadow-accent-volume transition-all hover:bg-accent-dark"
                >
                  Update Collection
                </button>
                <a
                    asp-action="Index" asp-controller="Collection" asp-route-id="@Model.Id"
                  class="w-36 rounded-full bg-white py-4 px-8 text-center font-semibold text-accent shadow-white-volume transition-all hover:bg-accent-dark hover:text-white hover:shadow-accent-volume"
                >
                  Cancel
                </a>
              </div>
            </div>

            <!-- Avatar -->
            <div class="flex space-x-5 md:w-1/2 md:pl-8">
              <div class="shrink-0">
                <figure class="relative inline-block">
                  <img
                       width="150"
                height="150"
                    src="~/assets/images/users/@User.Identity.Name/collections/@Model.Name/@ViewBag.Imgs[1]"
                    alt="collection avatar"
                    class="rounded-xl border-[5px] border-white dark:border-jacarta-600"
                  />
                  <div
                    class="group absolute -right-3 -bottom-2 h-8 w-8 overflow-hidden rounded-full border border-jacarta-100 bg-white text-center hover:border-transparent hover:bg-accent"
                  >
                    <input asp-for="LogoImg" accept="image/*" class="absolute top-0 left-0 w-full cursor-pointer opacity-0" />
                    <div class="flex h-full items-center justify-center">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        width="24"
                        height="24"
                        class="h-4 w-4 fill-jacarta-400 group-hover:fill-white"
                      >
                        <path fill="none" d="M0 0h24v24H0z" />
                        <path
                          d="M15.728 9.686l-1.414-1.414L5 17.586V19h1.414l9.314-9.314zm1.414-1.414l1.414-1.414-1.414-1.414-1.414 1.414 1.414 1.414zM7.242 21H3v-4.243L16.435 3.322a1 1 0 0 1 1.414 0l2.829 2.829a1 1 0 0 1 0 1.414L7.243 21z"
                        />
                      </svg>
                    </div>
                  </div>
                </figure>
              </div>
              <div class="mt-4">
                <span class="mb-3 block font-display text-sm text-jacarta-700 dark:text-white">Logo Image</span>
              </div>
            </div>
            <div class="flex space-x-5 md:w-1/2 md:pl-8">
              <div class="shrink-0">
                <figure class="relative inline-block">
                  <img
                       width="150"
                height="150"
                    src="~/assets/images/users/@User.Identity.Name/collections/@Model.Name/@ViewBag.Imgs[0]"
                    alt="collection avatar"
                    class="rounded-xl border-[5px] border-white dark:border-jacarta-600"
                  />
                  <div
                    class="group absolute -right-3 -bottom-2 h-8 w-8 overflow-hidden rounded-full border border-jacarta-100 bg-white text-center hover:border-transparent hover:bg-accent"
                  >
                    <input asp-for="MainImg" accept="image/*" class="absolute top-0 left-0 w-full cursor-pointer opacity-0" />
                    <div class="flex h-full items-center justify-center">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 24 24"
                        width="24"
                        height="24"
                        class="h-4 w-4 fill-jacarta-400 group-hover:fill-white"
                      >
                        <path fill="none" d="M0 0h24v24H0z" />
                        <path
                          d="M15.728 9.686l-1.414-1.414L5 17.586V19h1.414l9.314-9.314zm1.414-1.414l1.414-1.414-1.414-1.414-1.414 1.414 1.414 1.414zM7.242 21H3v-4.243L16.435 3.322a1 1 0 0 1 1.414 0l2.829 2.829a1 1 0 0 1 0 1.414L7.243 21z"
                        />
                      </svg>
                    </div>
                  </div>
                </figure>
              </div>
              <div class="mt-4">
                <span class="mb-3 block font-display text-sm text-jacarta-700 dark:text-white">Main Image</span>
              </div>
            </div>
          </div>
        </div>
      </section>
      <!-- end edit profile -->
      </form>
    </main>

Xhibiter/Xhibiter/Views/Collection/Explore.cshtml
@{
    ViewData["Title"] = "Explore";
}
<script src="~/assets/js/filtering.js"></script>
@model IEnumerable<NFTCollection>
    <main>
      <!-- Collections -->
      <section class="relative py-24">
        <picture class="pointer-events-none absolute inset-0 -z-10 dark:hidden">
          <img src="~/assets/img/gradient_light.jpg" alt="gradient" class="h-full w-full" />
        </picture>
        <div class="container">
          <h1 class="py-16 text-center font-display text-4xl font-medium text-jacarta-700 dark:text-white">
            Explore Collections
          </h1>

          <!-- Filters -->
          <div class="mb-8 flex flex-wrap items-center justify-between">
            <ul class="flex flex-wrap items-center">
                <li class=" my-1 mr-2.5">
                <a
                  href="#"
                  class="active category-link group flex h-9 items-center rounded-lg border border-jacarta-100 bg-white px-4 font-display text-sm font-semibold text-jacarta-500 transition-colors hover:border-transparent hover:bg-accent hover:text-white dark:border-jacarta-600 dark:bg-jacarta-900 dark:text-white dark:hover:border-transparent dark:hover:bg-accent dark:hover:text-white"
                >

                  <span>All</span>
                </a>
              </li>
                @foreach (var item in (List<Category>)ViewBag.Categories)
                {
              <li class=" my-1 mr-2.5">
                <a
                  href="#"
                  class=" category-link group flex h-9 items-center rounded-lg border border-jacarta-100 bg-white px-4 font-display text-sm font-semibold text-jacarta-500 transition-colors hover:border-transparent hover:bg-accent hover:text-white dark:border-jacarta-600 dark:bg-jacarta-900 dark:text-white dark:hover:border-transparent dark:hover:bg-accent dark:hover:text-white"
                >

                  <span>@item.Name</span>
                </a>
              </li>
                    
                }
            </ul>
          </div>

          <!-- Grid -->
              <div id="collections-container" class="grid grid-cols-1 gap-[1.875rem] md:grid-cols-2 lg:grid-cols-4">
                  <partial name="_CollectionsPartial" model="@Model"></partial>
              </div>

        </div>
      </section>
      <!-- end collections -->
    </main>

Xhibiter/Xhibiter/Views/Collection/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model NFTCollection
    <main class="pt-[5.5rem] lg:pt-24">
      <!-- Banner -->
      <div class="relative">
        <img src="~/assets/images/users/@Model.Creator.NFTUser.UserName/collections/@Model.Name/@Model.CoverImgUrl" alt="banner" class="h-[18.75rem] w-full object-cover" />
      </div>
      <!-- end banner -->

      <!-- Profile -->
      <section class="relative bg-light-base pb-12 pt-28 dark:bg-jacarta-800">
        <!-- Avatar -->
        <div class="absolute left-1/2 top-0 z-10 flex -translate-x-1/2 -translate-y-1/2 items-center justify-center">
          <figure class="relative">
            <img
                style="width:150px; height:150px;"
              src="~/assets/images/users/@Model.Creator.NFTUser.UserName/collections/@Model.Name/@Model.LogoImgUrl"
              alt="collection avatar"
              class="rounded-xl border-[5px] border-white dark:border-jacarta-600"
            />
            <div
              class="absolute -right-3 bottom-0 flex h-6 w-6 items-center justify-center rounded-full border-2 border-white bg-green dark:border-jacarta-600"
              data-tippy-content="Verified Collection"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                width="24"
                height="24"
                class="h-[.875rem] w-[.875rem] fill-white"
              >
                <path fill="none" d="M0 0h24v24H0z"></path>
                <path d="M10 15.172l9.192-9.193 1.415 1.414L10 18l-6.364-6.364 1.414-1.414z"></path>
              </svg>
            </div>
          </figure>
        </div>

        <div class="container">
          <div class="text-center">
            <h2 class="mb-2 font-display text-4xl font-medium text-jacarta-700 dark:text-white">@Model.Name</h2>
            <div class="mb-8">
              <span class="text-sm font-bold text-jacarta-400">Created by</span>
              <a asp-action="Index" asp-controller="Profile" asp-route-username="@Model.Creator.NFTUser.UserName" class="text-sm font-bold text-accent">@Model.Creator.NFTUser.UserName</a>
            </div>

            <div
              class="mb-8 inline-flex flex-wrap items-center justify-center rounded-xl border border-jacarta-100 bg-white dark:border-jacarta-600 dark:bg-jacarta-800"
            >
              <a
                href="#"
                class="w-1/2 rounded-l-xl border-r border-jacarta-100 py-4 hover:shadow-md dark:border-jacarta-600 sm:w-32"
              >
                <div class="mb-1 text-base font-bold text-jacarta-700 dark:text-white">@Model.NFTs.Count()</div>
                <div class="text-2xs font-medium tracking-tight dark:text-jacarta-400">Items</div>
              </a>
            </div>

            <p class="mb-6 mx-auto max-w-xl text-lg dark:text-jacarta-300">
              @Model.Description
            </p>
                        @if (User.Identity.IsAuthenticated && User.Identity.Name == Model.Creator.NFTUser.UserName)
                {
            <a
                asp-action="Edit" asp-route-id="@Model.Id" asp-controller="Collection"
                  class=" px-6 rounded-full bg-white py-3 text-center font-semibold text-accent shadow-white-volume transition-all hover:bg-accent-dark hover:text-white hover:shadow-accent-volume"
                >
                  Edit
                </a>
                }
          </div>
        </div>
      </section>
      <!-- end profile -->

      <!-- Collection -->
      <section class="relative py-24">
        <picture class="pointer-events-none absolute inset-0 -z-10 dark:hidden">
          <img src="~/assets/img/gradient_light.jpg" alt="gradient" class="h-full w-full" />
        </picture>
        <div class="container">
          <!-- Tabs Nav -->
          <ul
            class="nav nav-tabs mb-12 flex items-center justify-center border-b border-jacarta-100 dark:border-jacarta-600"
            role="tablist"
          >
            <li class="nav-item" role="presentation">
              <button
                class="nav-link active relative flex items-center whitespace-nowrap py-3 px-6 text-jacarta-400 hover:text-jacarta-700 dark:hover:text-white"
                id="items-tab"
                data-bs-toggle="tab"
                data-bs-target="#items"
                type="button"
                role="tab"
                aria-controls="items"
                aria-selected="true"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  width="24"
                  height="24"
                  class="mr-1 h-5 w-5 fill-current"
                >
                  <path fill="none" d="M0 0h24v24H0z" />
                  <path
                    d="M13 21V11h8v10h-8zM3 13V3h8v10H3zm6-2V5H5v6h4zM3 21v-6h8v6H3zm2-2h4v-2H5v2zm10 0h4v-6h-4v6zM13 3h8v6h-8V3zm2 2v2h4V5h-4z"
                  />
                </svg>
                <span class="font-display text-base font-medium">Items</span>
              </button>
            </li>
          </ul>

          <div class="tab-content">
            <!-- Items Tab -->
            <div class="tab-pane fade show active" id="items" role="tabpanel" aria-labelledby="items-tab">
              <!-- Grid -->
              <div class="grid grid-cols-1 gap-[1.875rem] md:grid-cols-2 lg:grid-cols-4">

                <partial name="_OnSalePartial" model="Model.NFTs"></partial>
                    </div>
              <!-- end grid -->
            </div>
            <!-- end items tab -->
          </div>
        </div>
      </section>
      <!-- end collection -->
    </main>