Xhibiter/Xhibiter/ViewModels/Profile/EditProfileVM.cs
using Xhibiter.Models;

namespace Xhibiter.ViewModels
{
    public class EditProfileVM
    {
        public string? Bio { get; set; }
        public IFormFile? CoverImg { get; set; }
        public IFormFile? ProfileImg { get; set; }
        public string? CoverImgUrl { get; set; }
        public string? ProfileImgUrl { get; set; }
        public string? InstagramLink { get; set; }
        public string? TwitterLink { get; set; }
        public string? ExternalLink { get; set; }

        public string Username { get; set; }

    }
}

Xhibiter/Xhibiter/ViewModels/Profile/ProfileDetailsVM.cs
using Xhibiter.Models;

namespace Xhibiter.ViewModels
{
    public class ProfileDetailsVM
    {
        public IEnumerable<NFT> OnSaleNFTs { get; set; }
        public IEnumerable<NFT> CreatedNFTs { get; set; }
        public IEnumerable<NFT> AuctionedNFTs { get; set; }
        public IEnumerable<NFT> HiddenNFTs { get; set; }
        public IEnumerable<NFTCollection> Collections { get; set; }
        public UserProfile User { get; set; }
        public IEnumerable<Activity> Activities { get; set; }

    }
}

Xhibiter/Xhibiter/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Xhibiter.DAL;
using Xhibiter.Models;
using Xhibiter.Utilities;
using Xhibiter.ViewModels;

namespace Xhibiter.Controllers
{
    public class ProfileController : Controller
    {
        UserManager<NFTUser> _userManager { get; }
        SignInManager<NFTUser> _signinManager { get; }
        AppDbContext _context { get; }
        IWebHostEnvironment _env { get; }

        public ProfileController(AppDbContext context, IWebHostEnvironment env, UserManager<NFTUser> userManager, SignInManager<NFTUser> signinManager)
        {
            _context = context;
            _env = env;
            _userManager = userManager;
            _signinManager = signinManager;
        }
        public async Task<IActionResult> Delete(string? username)
        {
            if (username is null || username.Length == 0 || username != User.Identity.Name) return BadRequest();
            UserProfile profile =await _context.UserProfiles.Include(u => u.NFTUser).Include(n=>n.Collections).FirstOrDefaultAsync(x => x.NFTUser.UserName == username);
            if (profile is null) return NotFound();
            profile.ProfileImageUrl.DeleteFile(_env.WebRootPath, $"assets/images/users/{User.Identity.Name}/profile");
            profile.CoverImageUrl.DeleteFile(_env.WebRootPath, $"assets/images/users/{User.Identity.Name}/cover");
            UserProfile admin = await _context.UserProfiles.Include(n=>n.NFTUser).FirstOrDefaultAsync(u => u.NFTUser.UserName == "admin");
            if (admin is null) return NotFound();
            var nfts = _context.NFTs.Include(n=>n.Metadata).Where(n => n.Metadata.CreatorId == profile.NFTUserId && n.OwnerId != profile.NFTUserId);
                foreach (var item in nfts)
                {
                item.Metadata.CreatorId = admin.NFTUserId;
                }
            foreach (var item in profile.Collections)
            {
                item.CreatorId = admin.Id;
            }
            _context.UserProfiles.Remove(profile);
            _context.NFTUsers.Remove(profile.NFTUser);
            await _context.SaveChangesAsync();
            await _signinManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
        public IActionResult Index(string? username)
        {
            if (username is null || username.Length == 0) return BadRequest();
            var user = _context.UserProfiles.Include(n => n.Collections).Include(u => u.NFTUser).Include(u => u.Bids).ThenInclude(b => b.Auction).FirstOrDefault(n => n.NFTUser.UserName == username);
            if (user is null) return NotFound();
            var OwnedNFTs = _context.NFTs.Include(n => n.Metadata).Include(n => n.Auction).Where(n => n.OwnerId == user.NFTUserId);
            var created = _context.NFTs.Include(n => n.Metadata).Include(n => n.Auction).Where(o => o.Metadata.CreatorId == user.NFTUserId && o.IsSale == true);
            var hidden = OwnedNFTs.Where(n => !n.IsSale && !n.IsAuctioned);
            var auctioned = OwnedNFTs.Where(n => !n.IsSale && n.IsAuctioned);
            var onSale = OwnedNFTs.Where(n => n.IsSale && !n.IsAuctioned);
            var collections = user.Collections;
            var activities = _context.Activities.Include(a => a.Bid.Auction.NFT).Include(a => a.Sale.From.Profile)
                .Include(a => a.Sale.To.Profile).Include(a=>a.Sale.NFT)
                .Where(a => a.SaleId != null && a.Sale.From.Profile.Id == user.Id || a.SaleId != null && a.Sale.To.Profile.Id == user.Id||a.BidId != null &&  a.Bid.BidderId == user.Id ).OrderByDescending(a=>a.Date);
            ProfileDetailsVM profile = new()
            {
                Activities = activities,
             AuctionedNFTs = auctioned,
             Collections = collections,
             HiddenNFTs = hidden,
             OnSaleNFTs = onSale,
             User = user,
             CreatedNFTs = created
            };
            return View(profile);
        }
        [Authorize]

        public IActionResult Edit(string? username)
        {
            if (username is null || username.Length == 0||username != User.Identity.Name) return BadRequest();
            UserProfile profile = _context.UserProfiles.Include(u => u.NFTUser).FirstOrDefault(x => x.NFTUser.UserName == username);
            if (profile is null) return NotFound();
            EditProfileVM editProfile = new EditProfileVM()
            {
                Bio = profile.Bio,
                CoverImgUrl = profile.CoverImageUrl,
                ProfileImgUrl = profile.ProfileImageUrl,
                TwitterLink = profile.TwitterLink,
                InstagramLink = profile.InstagramLink,
                ExternalLink = profile.ExternalLink
            };

            return View(editProfile);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Edit(EditProfileVM editProfile)
        {
            string name = User.Identity.Name;
            if (name is null || name.Length == 0) return BadRequest();
            var userr = await _userManager.FindByNameAsync(name);
            var coverImg = editProfile.CoverImg;
            var profileimg = editProfile.ProfileImg;
            var result = coverImg?.CheckValidate2(9);
            if (result?.Length > 0)
            {
                ModelState.AddModelError("", result);
            }
            result = profileimg?.CheckValidate2(9);
            if (result?.Length > 0)
            {
                ModelState.AddModelError("", result);
            }
            if (!ModelState.IsValid)
            {
                return View();
            }
            UserProfile profile =await _context.UserProfiles.Include(u => u.NFTUser).FirstOrDefaultAsync(x => x.NFTUser.UserName == name);
            if (profile is null) return NotFound();
            if (coverImg != null)
            {
                profile.CoverImageUrl?.DeleteFile(_env.WebRootPath, $"assets/images/users/{name}/cover");
                var newCover = coverImg.SaveFile(Path.Combine(_env.WebRootPath, "assets", "images", "users",User.Identity.Name,"cover"));
                profile.CoverImageUrl = newCover;
            }
            if (profileimg != null)
            {
                profile.ProfileImageUrl?.DeleteFile(_env.WebRootPath, $"assets/images/users/{name}/profile");
                var newProfile = profileimg.SaveImage(Path.Combine(_env.WebRootPath, "assets", "images", "users", User.Identity.Name, "profile"));
                profile.ProfileImageUrl = newProfile;
            }
            name = editProfile.Username;
            profile.Bio = editProfile.Bio;
            userr.UserName = editProfile.Username;
            profile.TwitterLink = editProfile.TwitterLink;
            profile.InstagramLink = editProfile.InstagramLink;
            profile.ExternalLink = editProfile.ExternalLink;
            await _userManager.UpdateAsync(userr);
            await _context.SaveChangesAsync();
            await _signinManager.SignInAsync(userr, false);
            return RedirectToAction(nameof(Index),new {username = name });
        }
    }
}

Xhibiter/Xhibiter/Views/Shared/Components/Profile/Default.cshtml
@model UserInfoVM
<div class="js-nav-dropdown group-dropdown relative">
              <button
                class="dropdown-toggle group ml-2 flex h-10 w-10 items-center justify-center rounded-full border border-jacarta-100 bg-white transition-colors hover:border-transparent hover:bg-accent focus:border-transparent focus:bg-accent dark:border-transparent dark:bg-white/[.15] dark:hover:bg-accent"
                id="profileDropdown"
                aria-expanded="false"
                data-bs-toggle="dropdown"
                aria-label="profile"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  viewBox="0 0 24 24"
                  width="24"
                  height="24"
                  class="h-4 w-4 fill-jacarta-700 transition-colors group-hover:fill-white group-focus:fill-white dark:fill-white"
                >
                  <path fill="none" d="M0 0h24v24H0z" />
                  <path
                    d="M11 14.062V20h2v-5.938c3.946.492 7 3.858 7 7.938H4a8.001 8.001 0 0 1 7-7.938zM12 13c-3.315 0-6-2.685-6-6s2.685-6 6-6 6 2.685 6 6-2.685 6-6 6z"
                  />
                </svg>
              </button>
              <div
                class="dropdown-menu group-dropdown-hover:visible lg:invisible !-right-4 !top-[85%] !left-auto z-10 hidden min-w-[14rem] whitespace-nowrap rounded-xl bg-white transition-all will-change-transform before:absolute before:-top-3 before:h-3 before:w-full group-dropdown-hover:opacity-100 dark:bg-jacarta-800 lg:absolute lg:grid lg:!translate-y-4 lg:py-4 lg:px-2 lg:opacity-0 lg:shadow-2xl"
                aria-labelledby="profileDropdown"
              >
                <button
                  class="js-copy-clipboard my-4 flex select-none items-center whitespace-nowrap px-5 font-display leading-none text-jacarta-700 dark:text-white"
                  data-tippy-content="Copy"
                >
                  <span class="max-w-[10rem] overflow-hidden text-ellipsis"
                    >@Model.WalletAddress</span
                  >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    width="24"
                    height="24"
                    class="ml-1 mb-px h-4 w-4 fill-jacarta-500 dark:fill-jacarta-300"
                  >
                    <path fill="none" d="M0 0h24v24H0z" />
                    <path
                      d="M7 7V3a1 1 0 0 1 1-1h13a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1h-4v3.993c0 .556-.449 1.007-1.007 1.007H3.007A1.006 1.006 0 0 1 2 20.993l.003-12.986C2.003 7.451 2.452 7 3.01 7H7zm2 0h6.993C16.549 7 17 7.449 17 8.007V15h3V4H9v3zM4.003 9L4 20h11V9H4.003z"
                    />
                  </svg>
                </button>

                <div class="mx-5 mb-6 rounded-lg border border-jacarta-100 p-4 dark:border-jacarta-600">
                  <span class="text-sm font-medium tracking-tight dark:text-jacarta-200">Balance</span>
                  <div class="flex items-center">
                    <svg
                      version="1.1"
                      xmlns="http://www.w3.org/2000/svg"
                      x="0"
                      y="0"
                      viewBox="0 0 1920 1920"
                      xml:space="preserve"
                      class="-ml-1 mr-1 h-[1.125rem] w-[1.125rem]"
                    >
                      <path fill="#8A92B2" d="M959.8 80.7L420.1 976.3 959.8 731z"></path>
                      <path fill="#62688F" d="M959.8 731L420.1 976.3l539.7 319.1zm539.8 245.3L959.8 80.7V731z"></path>
                      <path fill="#454A75" d="M959.8 1295.4l539.8-319.1L959.8 731z"></path>
                      <path fill="#8A92B2" d="M420.1 1078.7l539.7 760.6v-441.7z"></path>
                      <path fill="#62688F" d="M959.8 1397.6v441.7l540.1-760.6z"></path>
                    </svg>
                    <span class="text-lg font-bold text-green">@Model.Balance ETH</span>
                  </div>
                </div>
                <a
                  asp-action="Index" asp-controller="Profile" asp-route-username="@User.Identity.Name"
                  class="flex items-center space-x-2 rounded-xl px-5 py-2 transition-colors hover:bg-jacarta-50 hover:text-accent focus:text-accent dark:hover:bg-jacarta-600"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    width="24"
                    height="24"
                    class="h-4 w-4 fill-jacarta-700 transition-colors dark:fill-white"
                  >
                    <path fill="none" d="M0 0h24v24H0z"></path>
                    <path
                      d="M11 14.062V20h2v-5.938c3.946.492 7 3.858 7 7.938H4a8.001 8.001 0 0 1 7-7.938zM12 13c-3.315 0-6-2.685-6-6s2.685-6 6-6 6 2.685 6 6-2.685 6-6 6z"
                    ></path>
                  </svg>
                  <span class="mt-1 font-display text-sm text-jacarta-700 dark:text-white">My Profile</span>
                </a>
                <a
                  asp-action="Edit" asp-controller="Profile" asp-route-username="@User.Identity.Name"
                  class="flex items-center space-x-2 rounded-xl px-5 py-2 transition-colors hover:bg-jacarta-50 hover:text-accent focus:text-accent dark:hover:bg-jacarta-600"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    width="24"
                    height="24"
                    class="h-4 w-4 fill-jacarta-700 transition-colors dark:fill-white"
                  >
                    <path fill="none" d="M0 0h24v24H0z" />
                    <path
                      d="M9.954 2.21a9.99 9.99 0 0 1 4.091-.002A3.993 3.993 0 0 0 16 5.07a3.993 3.993 0 0 0 3.457.261A9.99 9.99 0 0 1 21.5 8.876 3.993 3.993 0 0 0 20 12c0 1.264.586 2.391 1.502 3.124a10.043 10.043 0 0 1-2.046 3.543 3.993 3.993 0 0 0-3.456.261 3.993 3.993 0 0 0-1.954 2.86 9.99 9.99 0 0 1-4.091.004A3.993 3.993 0 0 0 8 18.927a3.993 3.993 0 0 0-3.457-.26A9.99 9.99 0 0 1 2.5 15.121 3.993 3.993 0 0 0 4 11.999a3.993 3.993 0 0 0-1.502-3.124 10.043 10.043 0 0 1 2.046-3.543A3.993 3.993 0 0 0 8 5.071a3.993 3.993 0 0 0 1.954-2.86zM12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"
                    />
                  </svg>
                  <span class="mt-1 font-display text-sm text-jacarta-700 dark:text-white">Edit Profile</span>
                </a>
                <a
                  asp-action="Logout" asp-controller="Account"
                  class="flex items-center space-x-2 rounded-xl px-5 py-2 transition-colors hover:bg-jacarta-50 hover:text-accent focus:text-accent dark:hover:bg-jacarta-600"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    width="24"
                    height="24"
                    class="h-4 w-4 fill-jacarta-700 transition-colors dark:fill-white"
                  >
                    <path fill="none" d="M0 0h24v24H0z" />
                    <path
                      d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zM7 11V8l-5 4 5 4v-3h8v-2H7z"
                    />
                  </svg>
                  <span class="mt-1 font-display text-sm text-jacarta-700 dark:text-white">Sign out</span>
                </a>
              </div>
            </div>